# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XmlSigValidator < Formula
  desc ""
  homepage "https://github.com/lordtatty/homebrew-tools"
  version "0.19"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lordtatty/xml-sig-validatator/releases/download/v0.19/xml-sig-validatator_0.19_Darwin_arm64.tar.gz"
      sha256 "336914c9510c0c3765c4a01990e71d6c34369780850006247472cdaa0502483b"

      def install
        bin.install "xml-sig-validatator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lordtatty/xml-sig-validatator/releases/download/v0.19/xml-sig-validatator_0.19_Darwin_x86_64.tar.gz"
      sha256 "4a95af4686a0cc653babf16c32def40f61c4446526abc5a5ea513512d5f41477"

      def install
        bin.install "xml-sig-validatator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lordtatty/xml-sig-validatator/releases/download/v0.19/xml-sig-validatator_0.19_Linux_x86_64.tar.gz"
      sha256 "3cf27426ea47ace6942e7d3ed35f11ade8f60e5274f14f2ae5256ecd88998b04"

      def install
        bin.install "xml-sig-validatator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lordtatty/xml-sig-validatator/releases/download/v0.19/xml-sig-validatator_0.19_Linux_arm64.tar.gz"
      sha256 "3a0d8235c36ec20bafbc257193b04a3bb9a0907de4892f69a0f7531017ceaa0f"

      def install
        bin.install "xml-sig-validatator"
      end
    end
  end
end
